<?php

declare(strict_types=1);

namespace Devly\Utils\Tests;

use Devly\Utils\Tests\Fake\Foo;
use LogicException;
use PHPUnit\Framework\TestCase;

class SmartObjectTest extends TestCase
{
    protected Foo $foo;

    protected function setUp(): void
    {
        parent::setUp();

        $this->foo = new Foo();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        unset($this->foo);
    }

    public function testCallSpecialMethod(): void
    {
        $this->assertEquals('baz', $this->foo->get_bar());
        $this->assertEquals('baz', $this->foo->getBar());
    }

    public function testGetAndSetSpecialProperties(): void
    {
        $this->foo->bar = 'hello world!!';
        $this->assertEquals('hello world!!', $this->foo->bar);
    }

    public function testSetReadOnlyProperThrowsException(): void
    {
        $this->expectException(LogicException::class);

        $this->foo->baz = '';
    }
}
